### ISSUE TITLE
Indexation

### ISSUE THREAD

**Issue by malys** [LogeshG5/silverbullet-plantuml#1]
Hi,
To find easily your project, could you add these topics:

silverbullet
silverbullet-plugs
plantuml
....

Morevover you can add your plugins in https://github.com/gorootde/silverbullet-collection

Thanks for your work

**Comment by LogeshG5** [comment]
You are right. 

1. Updated topics. 
2. @juandjara was faster and added your [mindmap plugin](https://github.com/malys/silverbullet-mindmap) and this plugin to https://github.com/gorootde/silverbullet-collection
